dist: xenial
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
script:
  - python dymoprint --help
  - python dymoprint -v Tst
  - python dymoprint -v -qr Tst
  - python dymoprint -v -c code128 Tst
  - python dymoprint -v -qr qrencoded "qr_txt"
  - python dymoprint -v -c code128 Test "bc_txt"
